# ./configs/configs.yaml
training:
  batch_size: 128
  learning_rate: 0.0001
  num_epochs: 10
  weight_decay: 0.01
  grad_clip: 5.0
model:
  dropout_rate: 0.1
  num_classes: 20
paths:
  annotation: /NasData/home/lsh/mlcl/MLCL_2023/data/headgear/headgear.csv
  model_save_path: ./model/resnet50.pth
  dataset_path: /NasData/home/lsh/mlcl/MLCL_2023/data/headgear